language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adockernewbee/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true adockernewbee/react-test npm test

after_success:
  - docker build -t adockernewbee/multi-client ./client
  - docker build -t adockernewbee/multi-nginx ./nginx
  - docker build -t adockernewbee/multi-server ./server
  - docker build -t adockernewbee/multi-worker ./worker
